# Generated by Django 4.2.3 on 2023-07-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo della Categoria')),
                ('descrizione', models.CharField(max_length=250, verbose_name='Descrizione della Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('img', models.ImageField(default=None, upload_to='img/corsi')),
                ('contenuto', models.TextField()),
                ('data_inizio', models.DateField()),
                ('durata_ore', models.DecimalField(decimal_places=0, max_digits=3)),
                ('prezzo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.todocategory')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corsi',
            },
        ),
        migrations.CreateModel(
            name='Alunno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=200, verbose_name='Cognome')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('telefono', models.CharField(max_length=200, verbose_name='Telefono')),
                ('corso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corsi.corsi')),
            ],
            options={
                'verbose_name_plural': 'Alunni',
            },
        ),
    ]
