# Generated by Django 4.2.3 on 2023-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0002_alunno_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunno',
            name='img',
            field=models.ImageField(default=None, upload_to='img/utenti'),
        ),
    ]
